// Beat grid helpers. Everything important should land on these frames.
// Generated by make_soundtrack.py → public/audio/beats.json (bpm, framesPerBeat, sections).
export const makeGrid = (bpm: number, fps: number) => {
  const beat = (fps * 60) / bpm;
  return {
    beat, // frames per beat
    bar: beat * 4,
    b: (n: number) => Math.round(n * beat), // frame of beat n (0-based, may be fractional n)
    at: (barIndex: number, beatInBar = 0) => Math.round((barIndex * 4 + beatInBar) * beat),
  };
};
